site_name: activerecord
site_dir: .docs
site_description: PHP implementation of Active Record
repo_name: php-activerecord/activerecord
repo_url: https://github.com/php-activerecord/activerecord

nav:
  - Quick Start: quickstart.md


# Theme
theme:
  name: 'material'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
