site_name: activerecord
site_dir: .docs
site_description: PHP implementation of Active Record
repo_name: php-activerecord/activerecord
repo_url: https://github.com/php-activerecord/activerecord

nav:
  - Quick Start: quickstart.md
  - Upgrading from 1.x: upgrade.md
  - Conventions: conventions.md
  - Basic CRUD operations: crud.md
  - Finders: finders.md
  - Validations: validations.md
  - Callbacks: callbacks.md

# Theme
theme:
  name: 'material'
  timeout: 0

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
