site_name: activerecord
site_description: PHP implementation of Active Record
repo_name: php-activerecord/activerecord
repo_url: https://github.com/php-activerecord/activerecord
theme:
  name: mkdocs
docs_dir: docs/
markdown_extensions:
  - toc:
      permalink: true
nav:
- About: introduction.md
