site_name: activerecord
site_dir: .docs
site_description: PHP implementation of Active Record
repo_name: php-activerecord/activerecord
repo_url: https://github.com/php-activerecord/activerecord

nav:
  - Quick Start: quickstart.md
  - Upgrading from 1.x: upgrade.md
  - Conventions: conventions.md
  - Basic CRUD operations: crud.md
  - Finders: finders.md
  - Finders (dynamic): findersdynamic.md
  - Relationships:
      - Overview: relationships.md
      - has_one: hasone.md
      - has_many: hasmany.md
      - has_and_belongs_to_many: hasandbelongstomany.md
  - Validations:
      - Overview: validations.md
      - validates_length_of: validateslengthof.md
      - validates_presence_of: validatespresenceof.md
      - validates_format_of: validatesformatof.md
      - validates_inclusion_of: validatesinclusionof.md
      - validates_exclusion_of: validatesexclusionof.md
      - validates_uniqueness_of: validatesuniquenessof.md
      - validates_numericality_of: validatesnumericalityof.md
  - Callbacks: callbacks.md

# Theme
theme:
  name: 'material'
  timeout: 0
  logo: 'https://user-images.githubusercontent.com/773172/277515784-b0ad0885-9401-4ffa-b677-43590dc18f29.png'
  favicon: 'https://user-images.githubusercontent.com/773172/277515784-b0ad0885-9401-4ffa-b677-43590dc18f29.png'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
